languages= {
    'Arabic (Egypt)' : ['ar', 'ar-EG*','Microsoft Server Speech Text to Speech Voice (ar-EG, Hoda)' ],
    'Arabic (Saudi Arabia)': ['ar','ar-SA', 'Microsoft Server Speech Text to Speech Voice (ar-SA, Naayf)'],
    'Bulgarian': ['bg','bg-BG', 'Microsoft Server Speech Text to Speech Voice (bg-BG, Ivan)'],
    'Catalan (Spain)':['ca', 'ca-ES', 'Microsoft Server Speech Text to Speech Voice (ca-ES, HerenaRUS)'],
    'Czech': ['cs', 'cs-CZ','Microsoft Server Speech Text to Speech Voice (cs-CZ, Jakub)' ],
    'Danish': ['da', 'da-DK','Microsoft Server Speech Text to Speech Voice (da-DK, HelleRUS)' ],
    'German (Austria)': ['de', 'de-AT', ],
    'German (Switzerland)': ['de', 'de-CH','Microsoft Server Speech Text to Speech Voice (de-CH, Karsten)' ],
    'German(Germany)': ['de', 'de-DE','Microsoft Server Speech Text to Speech Voice (de-DE, HeddaRUS)' ],
    'Greek': ['el', 'el-GR', 'Microsoft Server Speech Text to Speech Voice (el-GR, Stefanos)' ],
    'English (Australia)': ['en', 'en-AU', 'Microsoft Server Speech Text to Speech Voice (en-AU, Catherine)'],
    'English (Canada)': ['en', 'en-CA', 'Microsoft Server Speech Text to Speech Voice (en-CA, Linda)'],
    'English(UK)': ['en', 'en-GB', 'Microsoft Server Speech Text to Speech Voice (en-GB, Susan, Apollo)'],
    'English (Ireland)': ['en', 'en-IE', 'Microsoft Server Speech Text to Speech Voice (en-IE, Sean)'],
    'English (India)' : ['en', 'en-IN','Microsoft Server Speech Text to Speech Voice (en-IN, Heera, Apollo)' ],
    'English(US)': ['en', 'en-US','Microsoft Server Speech Text to Speech Voice (en-US, ZiraRUS)'],
    'Spanish (Spain)':['es', 'es-ES', 'Microsoft Server Speech Text to Speech Voice (es-ES, Laura, Apollo)'],
    'Spanish (Mexico)': ['es', 'es-MX','Microsoft Server Speech Text to Speech Voice (es-MX, HildaRUS)' ],
    'Finnish': ['fi', 'fi-FI', 'Microsoft Server Speech Text to Speech Voice (fi-FI, HeidiRUS'],
    'French (Canada)': ['fr', 'fr-CA', 'Microsoft Server Speech Text to Speech Voice (fr-CA, Caroline)'],
    'French (Switzerland)': ['fr', 'fr-CH', 'Microsoft Server Speech Text to Speech Voice (fr-CH, Guillaume)'],
    'French (France)': ['fr', 'fr-FR','Microsoft Server Speech Text to Speech Voice (fr-FR, Julie, Apollo)'],
    'Hebrew (Israel)': ['he', 'he-IL','Microsoft Server Speech Text to Speech Voice (he-IL, Asaf)'],
    'Hindi': ['hi', 'hi-IN', 'Microsoft Server Speech Text to Speech Voice (hi-IN, Kalpana, Apollo)'],
    'Croatian': ['hr', 'he-HR', 'Microsoft Server Speech Text to Speech Voice (hr-HR, Matej)'],
    'Hungarian':['hu', 'hu-HU','Microsoft Server Speech Text to Speech Voice (hu-HU, Szabolcs)'],
    'Indonesian': ['id', 'id-ID', 'Microsoft Server Speech Text to Speech Voice (id-ID, Andika)'],
    'Italian': ['it', 'it-IT', 'Microsoft Server Speech Text to Speech Voice (it-IT, Cosimo, Apollo)'],
    'Japanese': ['ja', 'ja-JP', 'Microsoft Server Speech Text to Speech Voice (ja-JP, Ayumi, Apollo)'],
    'Korean': ['ko', 'ko-KR','Microsoft Server Speech Text to Speech Voice (ko-KR, HeamiRUS)' ],
    'Malay' : ['ms', 'ms-MY', 'Microsoft Server Speech Text to Speech Voice (ms-MY, Rizwan)'],
    'Norwegian' : ['nb', 'nb-NO', 'Microsoft Server Speech Text to Speech Voice (nb-NO, HuldaRUS)'],
    'Dutch' :['nl', 'nl-NL', 'Microsoft Server Speech Text to Speech Voice (nl-NL, HannaRUS)'],
    'Polish' : ['pl', 'pl-PL', 'Microsoft Server Speech Text to Speech Voice (pl-PL, PaulinaRUS)'],
    'Portuguese (Brazil)': ['pt', 'pt-BR', 'Microsoft Server Speech Text to Speech Voice (pt-BR, HeloisaRUS)'],
    'Portuguese (Portugal)': ['pt', 'pt-PT', 'Microsoft Server Speech Text to Speech Voice (pt-PT, HeliaRUS)'],
    'Romanian': ['ro', 'ro-RO', 'Microsoft Server Speech Text to Speech Voice (ro-RO, Andrei)'],
    'Russian': ['ru', 'ru-RU', 'Microsoft Server Speech Text to Speech Voice (ru-RU, Irina, Apollo)'],
    'Slovak' : ['sk', 'sk-SK', 'Microsoft Server Speech Text to Speech Voice (sk-SK, Filip)'],
    'Slovenian': ['sl', 'sl-SI', 'Microsoft Server Speech Text to Speech Voice (sl-SI, Lado)'],
    'Swedish': ['sv', 'sv-SE', 'Microsoft Server Speech Text to Speech Voice (sv-SE, HedvigRUS)'],
    'Tamil': ['ta', 'ta-IN', 'Microsoft Server Speech Text to Speech Voice (ta-IN, Valluvar)'],
    'Telgu': ['te', 'te-IN', 'Microsoft Server Speech Text to Speech Voice (te-IN, Chitra)'],
    'Thai': ['th', 'th-TH', 'Microsoft Server Speech Text to Speech Voice (th-TH, Pattara)'],
    'Turkish': ['tr', 'tr-TR', 'Microsoft Server Speech Text to Speech Voice (tr-TR, SedaRUS)'],
    'Vietnamese': ['vi', 'vi-VN','Microsoft Server Speech Text to Speech Voice (vi-VN, An)'],
    'Chinese (Mainland)':['zh', 'zh-CN', 'Microsoft Server Speech Text to Speech Voice (zh-CN, HuihuiRUS)'],
    'Chinese (Hong Kong)':['zh', 'zh-HK', 'Microsoft Server Speech Text to Speech Voice (zh-HK, Tracy, Apollo)'],
    'Chinese (Taiwan)': ['zh', 'zh-TW', 'Microsoft Server Speech Text to Speech Voice (zh-TW, Yating, Apollo)']
}